services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: devops_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - back_net

  seed_runner:
    build: .
    command: ["python", "seed/run_seed.py"]
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/devops_db
    volumes:
      - seed_output:/seed_output
    networks:
      - back_net
    restart: "no"

  app:
    build: .
    depends_on:
      - db
      - seed_runner
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/devops_db
    networks:
      - front_net
      - back_net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - front_net

volumes:
  db_data:
  nginx_logs:
  seed_output:

networks:
  front_net:
  back_net:
